<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>injectionSelector</key>
	<string>-source.diff</string>
	<key>name</key>
	<string>Trailing Whitespace</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.whitespace.trailing</string>
				</dict>
			</dict>
			<key>match</key>
			<string>((\S)([^\S\n\f\r]+)$)</string>
		</dict>
	</array>
	<key>uuid</key>
	<string>D65149ED-CC2B-4393-9084-2DA7C1B7B12B</string>
</dict>
</plist>
